name: wapnp-forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - geopandas
  - cartopy>=0.21
  - jupyterlab
  - ipywidgets
  - rasterio
  - rasterstats
  - folium
  - matplotlib
  - pandas
  - numpy
